version: '3'

services:
  database:
    image: postgres
    container_name: pruchasesdb
    restart: always
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=pruchasesdb
      - POSTGRES_DB=pruchasesdb
    volumes:
      - pgdata:/data/postgres
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:6.0.0
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  pgdata:
    driver: local